/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CharactersIndexRouteImport } from './routes/characters.index'
import { Route as CharactersCharacterNameRouteImport } from './routes/characters.$characterName'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersIndexRoute = CharactersIndexRouteImport.update({
  id: '/characters/',
  path: '/characters/',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersCharacterNameRoute = CharactersCharacterNameRouteImport.update({
  id: '/characters/$characterName',
  path: '/characters/$characterName',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/characters/$characterName': typeof CharactersCharacterNameRoute
  '/characters': typeof CharactersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/characters/$characterName': typeof CharactersCharacterNameRoute
  '/characters': typeof CharactersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/characters/$characterName': typeof CharactersCharacterNameRoute
  '/characters/': typeof CharactersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/characters/$characterName' | '/characters'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/characters/$characterName' | '/characters'
  id: '__root__' | '/' | '/characters/$characterName' | '/characters/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CharactersCharacterNameRoute: typeof CharactersCharacterNameRoute
  CharactersIndexRoute: typeof CharactersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/': {
      id: '/characters/'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/$characterName': {
      id: '/characters/$characterName'
      path: '/characters/$characterName'
      fullPath: '/characters/$characterName'
      preLoaderRoute: typeof CharactersCharacterNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CharactersCharacterNameRoute: CharactersCharacterNameRoute,
  CharactersIndexRoute: CharactersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
